### ISSUE TITLE
Exception: Already Connected

### ISSUE THREAD

**Issue by owbpq** [GeeTeam/gtapp-android#1]
问题发生在在 [Geetest.java](https://github.com/GeeTeam/gtapp-android/blob/master/sdk/src/main/java/com/geetest/android/sdk/Geetest.java) 里面，
当我是用 https 请求时，会出现 Exception: Already Connected 异常，原因在于 171 行代码 sslReadConnection.getHeaderFields() 实际上已经打开了连接，所以后续在 181 行 sslReadConnection.setDoInput(true); 调整连接的属性时会报错。

可以参考[StackOverflow](http://stackoverflow.com/questions/15899482/exception-already-connected-httpsurlconnection)

# 即原来的代码：
<pre>
                HttpsURLConnection sslReadConnection = (HttpsURLConnection) url.openConnection();
                mSSLReadConnection = sslReadConnection;

                cookieManager = new CookieManager();

                Map<String, List<String>> headerFields = sslReadConnection.getHeaderFields();
                if (headerFields.get("Set-Cookie") != null) {
                    List<String> cookiesHeader = headerFields.get("Set-Cookie");
                    if(cookiesHeader != null) {
                        for (String cookie : cookiesHeader) {
                            cookieManager.getCookieStore().add(null, HttpCookie.parse(cookie).get(0));
                        }
                    }
                }

                sslReadConnection.setDoInput(true);
                sslReadConnection.setDoOutput(false);
                sslReadConnection.setRequestMethod("GET");

                sslReadConnection.setConnectTimeout(mTimeout/2);

                sslReadConnection.setReadTimeout(mTimeout/2);

                sslReadConnection.connect();
</pre>

# 应该改成：
<pre>
                HttpsURLConnection sslReadConnection = (HttpsURLConnection) url.openConnection();
                mSSLReadConnection = sslReadConnection;
                cookieManager = new CookieManager();
                sslReadConnection.setDoInput(true);
                sslReadConnection.setDoOutput(false);
                sslReadConnection.setRequestMethod("GET");

                sslReadConnection.setConnectTimeout(mTimeout/2);

                sslReadConnection.setReadTimeout(mTimeout/2);

                sslReadConnection.connect();

                Map<String, List<String>> headerFields = sslReadConnection.getHeaderFields();
                if (headerFields.get("Set-Cookie") != null) {
                    List<String> cookiesHeader = headerFields.get("Set-Cookie");
                    if(cookiesHeader != null) {
                        for (String cookie : cookiesHeader) {
                            cookieManager.getCookieStore().add(null, HttpCookie.parse(cookie).get(0));
                        }
                    }
                }
</pre>

**Comment by NikoXu** [comment]
谢谢反馈，我们已经在本地版本修复。
待本地的新功能完成后，会一并更新上来。

**Comment by NikoXu** [comment]
@pheynix 谢谢反馈，我们已经在本地版本修复。
待本地的新功能完成后，会一并更新上来。

**Comment by messense** [comment]
@NikoXu Same issue.

请尽快更新，谢谢。
