### ISSUE TITLE
所需要的最少的权限？

### ISSUE THREAD

**Issue by messense** [GeeTeam/gtapp-android#3]
文档里面没有说明需要哪些权限，最少能运行的权限是？

```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
```

**Comment by NikoXu** [comment]
```
	<uses-permission android:name="android.permission.INTERNET" />
   	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
	<uses-permission android:name="android.permission.READ_PHONE_STATE" />
```
Sorry. We don't notice this **important** information in our dev-doc. I'll add it soon.

**Comment by messense** [comment]
`CHANGE_WIFI_STATE` 这个权限为什么需要？

另外，希望考虑一下 Android M 的运行时权限。

**Comment by guxiaonian** [comment]
<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />

**Comment by guxiaonian** [comment]
use Build.VERSION.SDK>INT>=23 to judge

**Comment by messense** [comment]
@guxiaonian Still have to request permissions manually at runtime.

**Comment by guxiaonian** [comment]
ContextCompat.checkSelfPermission(Context context,String permission)
ActivityCompat.requestPermissions(Activity activity, String[] permissions, int requestCode)
ActivityCompat.shouldShowRequestPermissionRationale(Activity activity,String permission)
要用到危险权限，READ_PHONE_STATE时，用Build.VERSION.SDK_INT >= 23 &&
                        ContextCompat.checkSelfPermission(getActivity(), Manifest.permission.READ_PHONE_STATE) != PackageManager.PERMISSION_GRANTED)对其判断，再用onRequestPermissionsResult对其进行授权处理

**Comment by messense** [comment]
@guxiaonian 嗯，不知道这个能不能直接在 SDK 而不是 Application 中做？

**Comment by guxiaonian** [comment]
因为程序都不止一个危险权限，比如CAMERA这一些，可以进行批量申请，批量申请权限很简单，只需要字符串数组放置多个权限即可。

**Comment by messense** [comment]
@guxiaonian 从用户体验上来说，希望和 iOS 一样在使用某个功能需要几个权限的时候一起申请比较好。

**Comment by guxiaonian** [comment]
是的，我们的SDK中只有一个危险权限，具体用到哪一些具体处理比较好
