### ISSUE TITLE
加载验证图片时被CORS禁止

### ISSUE THREAD

**Issue by mahong978** [GeeTeam/gtapp-android#4]
在加载验证码需要的图片时，chromium给出的log信息是：
I/chromium: [INFO:CONSOLE(0)] "Image from origin 'XXXX' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://115.28.113.153' is therefore not allowed access.", source: http://115.28.113.153/static/appweb/app-index.html?XXXX

请问这种问题该如何解决呢？

**Comment by NikoXu** [comment]
您好，请问您使用的什么版本的sdk？
请根据GtDialog 中的request url中的sdk version为准。

是否有修改webviewclient设置？

**Comment by mahong978** [comment]
android sdk是API23，gtapp sdk用的是2.16.12.15.1
没有修改WebViewClient设置

**Comment by guxiaonian** [comment]
尝试一下在静态资源服务器上，增加一个头信息：Access-Control-Allow-Origin *

**Comment by NikoXu** [comment]
@mahong978 稍后 我们给你提供一个新的sdk
我们在请求静态服务器超时后会自动切换用ip访问我们的资源
而115.28.113.153这个ip是备选方案, 我们已经不在对外使用

**Comment by NikoXu** [comment]
@mahong978 可以尝试一下最新更新上去的sdk

**Comment by mahong978** [comment]
@NikoXu 感谢你的回复
我使用了更新的sdk
之前的问题没有了，但是现在仍无法得到滑动验证码图片
根据Log，在输出I/GTWebView: webview did start后，一直没能得到回复

Debug定位到的源头是WebClientEx的onReceivedError得到回调
其参数之一的WebResourceRequest的方法是GET，url是"https://XXX/geetest/static/js/geetest.5.7.0.js"
另一个参数WebResourceError的错误描述是"net::ERR_CONNECTION_TIMED_OUT"
看起来似乎是获取该js文件超时了

请问如何解决呢？

**Comment by guxiaonian** [comment]
@mahong978 您好，明天早上帮您解决

**Comment by guxiaonian** [comment]
试一下在webview中添加一个超时器，执行超时后的动作

**Comment by guxiaonian** [comment]
@mahong978 试一下在webview中添加一个超时器，执行超时后的动作
